[phases.setup]
nixPkgs = ["go", "gcc", "musl-dev"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["CGO_ENABLED=1 go build -o tinygo ./cmd/server"]

[phases.deploy]
cmds = ["cp -r web ./web"]

[start]
cmd = "./tinygo"
