[build]
builder = "nixpacks"

[deploy]
startCommand = "./bin/urlshort"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
TINYGO_LOG_LEVEL = "info"
TINYGO_LOG_FORMAT = "json"
TINYGO_DATABASE_DRIVER = "sqlite"
TINYGO_DATABASE_DSN = "data/tinygo.db"
