# TinyGo URL Shortener Configuration
# This file supports YAML format with viper

# Server configuration
addr: ":8080"
base_url: "http://localhost:8080"  # Used for generating short URLs

# Data storage
data_file: "data/links.json"

# Short code generation
code_length: 7

# Logging configuration
log_level: "info"    # debug, info, warn, error
log_format: "text"   # text, json

# Database configuration
database:
  driver: "sqlite"           # sqlite, postgres, mysql
  dsn: "data/tinygo.db"      # database connection string
  log_level: "warn"          # gorm log level: silent, error, warn, info

# Authentication configuration
# IMPORTANT: Set these via environment variables for security!
# export TINYGO_AUTH_USERNAME="your_username"
# export TINYGO_AUTH_PASSWORD="your_password"
auth:
  username: ""               # Set via TINYGO_AUTH_USERNAME env var
  password: ""               # Set via TINYGO_AUTH_PASSWORD env var
  session_key: "tinygo_session"  # session cookie name
  session_max_age: 3600      # session timeout in seconds (1 hour)
