name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Check for tests
      run: |
        if find . -name "*_test.go" | grep -q .; then
          echo "Running tests..."
          go test -v ./...
        else
          echo "No test files found, skipping tests"
        fi
      
    - name: Build application
      run: go build -o tinygo ./cmd/server
      
    - name: Verify web assets
      run: |
        ls -la web/
        ls -la web/templates/
        ls -la web/static/
